services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Repositories
    AppBundle\Repository\UserRepository:
        factory: "doctrine:getRepository"
        arguments: ["AppBundle:User"]
